---
- name: Check install directory present or not
  stat: path={{ remote_location }}
  register: location

- name: Creating user group if not exists
  group: name={{ remote_group }} state=present

- name: Creating user if not exists
  user: name={{ remote_user }} shell=/bin/bash groups={{ remote_group }} append=yes

- name: Creating install directory if not present
  file:
    path: "{{ remote_location }}"
    state: directory
    owner: "{{ remote_user }}"
    group: "{{ remote_group }}"
    recurse: yes
    mode: 0755

