---
#To download activemq paackage
- name: Downloading amq-{{ amq_version }}
  get_url: 
    url: "{{ amq_url }}"
    dest: "{{ amq_install_dir }}/apache-activemq-{{ amq_version }}-bin.tar.gz"
    force: no
#    owner: "{{ amq_user }}"
#    group: "{{ amq_group }}"
  register: result
  until: result|success
  retries: 5
  delay: 2

#Extracting the package
- name: Extracting downloaded package
  unarchive:
    src: "{{ amq_install_dir }}/apache-activemq-{{ amq_version }}-bin.tar.gz"
    dest: "{{ amq_install_dir }}"
    remote_src: true

- name: create user if not exist
  user:
    name: "{{ amq_user }}"
    state: present

- name: Create user group if not exist
  group: name={{ amq_group }}  state=present

#File permissions
- name: Changing file permissions
  file: 
    path: "{{ amq_install_dir }}/apache-activemq-{{ amq_version }}"
    owner: "{{ amq_user }}" 
    group: "{{ amq_group }}"
    recurse: yes

