--- 
- name: unarchive the etcd
  unarchive:
    src: '{{ etcd_download_url }}'      #https://github.com/coreos/etcd/releases/download/v3.1.8/etcd-v3.1.8-linux-amd64.tar.gz
    dest: '{{ etcd_download_dir }}'
    remote_src: True

- name: Create etcd config directory
  file: 
    path: '{{ etcd_config }}' 
    state: directory

- name: Write etcd config file
  template: 
    src: etcd.conf.j2 
    dest: '{{ etcd_config }}/etcd.conf'
  register: etc_config

- name: print something 
  debug:
    msg: '{{ etc_config }}'

- name: Copy the binary to the location
  copy:
    src: '{{ etcd_download_dir }}/{{ etcd_release }}/{{ item }}'
    dest: '{{ etcd_dir }}'
    mode: 755
    remote_src: true
  with_items:
    - etcd
    - etcdctl

- name: Copying the service script
  copy:
    src: etcd
    mode: 755
    dest: /etc/init.d
    
- name: Enable and start etcd
  when: etc_config|succeded
  service: name=etcd enabled=no state=started

- name: Retart etcd
  service: name=etcd state=restarted
  when: etc_config|changed 
  register: etcd_started



