--- 
- name: Upgrade pip of python3
  command: "python{{ PYTHON_BINARY }} -m pip install --upgrade pip"

- name: Installing python packages
  command: "python{{ PYTHON_BINARY }} -m pip install --upgrade {{ item }}"
  with_items: "{{ PYTHON_PACKAGES }}"

- name: Installing Cuda dependencies 
  apt:
    name: libcupti-dev
    state: latest
  when: GPU_ENABLED #when the machine is GPU enabled (cuda compatible)

- name: Install Tensorflow GPU
  command: "python{{ PYTHON_BINARY }} -m pip install --upgrade {{ GPU_PACKAGE }}"
  when: GPU_ENABLED #When the machine is GPU enabled

- name: Install Tensorflow CPU
  command: "python{{ PYTHON_BINARY }} -m pip install --upgrade {{ CPU_PACKAGE }}"
  when: not GPU_ENABLED #When the machine is not CPU enabled 
 
