---
- name: Testing if python3.5 is already installed
  command: python3.5 --version
  register: python_status
  ignore_errors: true


- name: Download python3.5 source
  get_url:
    url: "{{ PYTHON_URL }}/{{ PYTHON_VERSION }}/Python-{{ PYTHON_VERSION }}.tgz"
    dest: /tmp
  when: python_status.rc != 0
    
- name: Unarchive the python3.5 source
  unarchive: 
    src: "/tmp/Python-{{ PYTHON_VERSION }}.tgz"
    remote_src: true
    dest: "{{ PYTHON_SOURCE_LOCATION }}"  
  when: python_status.rc != 0
   
- name: Installing Python dependecies for building
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ PYTHON_DEPENDENCIES }}"
  when: python_status.rc != 0

- name: Configuring before building Python from source
  command: ./configure
  args: 
    chdir: "{{ PYTHON_SOURCE_LOCATION }}/Python-{{ PYTHON_VERSION }}"
  when: python_status.rc != 0

- name: Building Python from source
  command: make altinstall  #altinstall so that python2.7 is not overridden by the installation
  args:
    chdir: "{{ PYTHON_SOURCE_LOCATION }}/Python-{{ PYTHON_VERSION }}"
  when: python_status.rc != 0

- name: Cleaning up the tarball
  file:
    path: "/tmp/Python-{{ PYTHON_VERSION }}.tgz"
    state: absent
