---
#Download latest and stable version
- name: Downloading redis-stable package
  get_url:
    url: "{{ redis_url }}"
    dest: "{{ redis_install_dir }}"
    force: no
    owner: "{{ redis_user }}"
    group: "{{ redis_group }}"
  register: result
  until: result|success
  retries: 5
  delay: 2

#Extracting the package

- name: Unarchiving packagge
  unarchive:
    src: "{{ redis_install_dir }}/redis-stable.tar.gz"
    dest: "{{ redis_install_dir }}"
    remote_src: true

#Setting file permissions
- name: Setting file permissions
  file:
    path: "{{ redis_home_dir }}"
    owner: "{{ redis_user }}"
    group: "{{ redis_group }}"
    recurse: yes

