- name: Add java repo
  apt_repository:
    repo: "{{ apt_java_repo }}"
    state: present
    update_cache: yes
  when: install_java

- name: Accept Oracle license prior JDK installation
  debconf: name={{ apt_java_package }} question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
  when: install_java
  ignore_errors: "{{ ansible_check_mode }}"
#If you want to skip, or ignore errors on some tasks in check mode you can use a boolean magic variable
- name: Install Java
  apt: name={{ apt_java_package }} state=present update_cache=yes cache_valid_time={{ apt_cache_valid_time }}
  when: install_java
  ignore_errors: "{{ ansible_check_mode }}"
